# Generated by Django 4.1.7 on 2023-02-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article title', models.CharField(max_length=50)),
                ('name poster', models.CharField(max_length=50)),
                ('article text', models.TextField(max_length=255)),
            ],
        ),
    ]
